### ISSUE TITLE
User Restrictions

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#83]
- [x] Lock down account creation to only specified users

- [x] Build create user page for SNL admin
  - Allow deletion of old users
  - Allow user restrictions (ie. read-write / read-only)

- [x] Remove public facing sign up page

**Comment by isaiahnields** [comment]
Because AWS is a bit annoying about signing up user's with users, I've opted for the "Create User" button to just send me an email directly. This obviously won't work if we onboard more people, but for now it should work A-OK. This will also make sure we know every time when someone wants to sign up.
